- name: Git setup email
  git_config:
    name: user.email
    scope: global
    value: "benjamin.petermann@gmx.at"
  tags:
    - git
- name: Git setup name
  git_config:
    name: user.name
    scope: global
    value: "bpetermann"
