- name: Install nodejs and npm
  become: true
  apt:
    name: ["nodejs", "npm"]
  tags:
    - install
    - node

- name: npmjs prefix
  shell: mkdir -p ~/.local/.npm-global
  tags:
    - install
    - node

- name: npmjs global settings
  shell: npm config set prefix '~/.local/.npm-global'
  tags:
    - install
    - node

- name: Install n
  npm:
    name: n
    global: yesF
  tags:
    - install
    - node

- name: Install Node v16.16.0
  shell: n v16.16.0
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/.npm-global/bin:{{ ansible_env.PATH }}"
  tags:
    - install
    - node